import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 flex flex-col min-h-screen">
        <nav className="w-full p-4 bg-black text-white flex justify-between">
          <h1 className="font-bold flex">Skill Swap</h1>
          <div className="space-x-4">
            <a href="/home">Home</a>
            <a href="/about">About</a>            
            <a href="/dashboard">Dashboard</a>
          </div>
        </nav>
        <main className="p-6 flex-grow">{children}</main>
        <footer className="w-full p-4 bg-black text-white text-center">
          <p>&copy; 2025 Skill Swap</p>
        </footer>
      </body>
    </html>
  );
}